# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.nameEdit = QtWidgets.QLineEdit(Form)
        self.nameEdit.setGeometry(QtCore.QRect(20, 20, 360, 30))
        self.nameEdit.setObjectName("nameEdit")
        self.roastEdit = QtWidgets.QLineEdit(Form)
        self.roastEdit.setGeometry(QtCore.QRect(20, 60, 360, 30))
        self.roastEdit.setObjectName("roastEdit")
        self.groundEdit = QtWidgets.QLineEdit(Form)
        self.groundEdit.setGeometry(QtCore.QRect(20, 100, 360, 30))
        self.groundEdit.setObjectName("groundEdit")
        self.tasteEdit = QtWidgets.QLineEdit(Form)
        self.tasteEdit.setGeometry(QtCore.QRect(20, 140, 360, 30))
        self.tasteEdit.setObjectName("tasteEdit")
        self.priceEdit = QtWidgets.QLineEdit(Form)
        self.priceEdit.setGeometry(QtCore.QRect(20, 180, 360, 30))
        self.priceEdit.setObjectName("priceEdit")
        self.volumeEdit = QtWidgets.QLineEdit(Form)
        self.volumeEdit.setGeometry(QtCore.QRect(20, 220, 360, 30))
        self.volumeEdit.setObjectName("volumeEdit")
        self.saveButton = QtWidgets.QPushButton(Form)
        self.saveButton.setGeometry(QtCore.QRect(140, 260, 120, 30))
        self.saveButton.setObjectName("saveButton")

        self.retranslateUi(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.nameEdit.setPlaceholderText(_translate("Form", "Название"))
        self.roastEdit.setPlaceholderText(_translate("Form", "Обжарка"))
        self.groundEdit.setPlaceholderText(_translate("Form", "Тип (молотый / зерна)"))
        self.tasteEdit.setPlaceholderText(_translate("Form", "Вкус"))
        self.priceEdit.setPlaceholderText(_translate("Form", "Цена"))
        self.volumeEdit.setPlaceholderText(_translate("Form", "Объём"))
        self.saveButton.setText(_translate("Form", "Сохранить"))
